version: '3.8'
services: # app components like ui , logs , db 
  venkat-ui-service:
    image: venkat-webui:version$BUILD_NUMBER 
    build:
      context: . # location of dockerfile 
      dockerfile: Dockerfile  # name of Dockerfile 
    container_name: venkat-web-c1 # name of container 
    ports:
      - 3333:80 # you can use 1024-5000 range 